vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        dogs_images:
            uri_prefix: media/dogs_images
            upload_destination: '%kernel.project_dir%/public/media/dogs_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true